/*
  DEMO DATA — placeholder manifest.

  This file mimics the exact shape that the real `photos.json` / `videos.json`
  generated by the Drive-fetch script will have. When the real files are
  uploaded, this file gets replaced by generated JSON with the same fields —
  no other code in the site needs to change.

  Schema:
    id        -> Google Drive file ID
    name      -> display name / caption
    category  -> "holud" | "wedding"
    type      -> "photo" | "video"
    cover     -> (optional) marks this item as a featured/collage image
*/

function makePlaceholderItems(category, count, type = "photo") {
  const items = [];
  for (let i = 1; i <= count; i++) {
    items.push({
      id: `DEMO-${category}-${type}-${i}`,
      name: `${category === "holud" ? "Holud" : "Wedding"} ${type === "video" ? "clip" : "moment"} ${i}`,
      category,
      type,
      cover: i <= 4
    });
  }
  return items;
}

const MEDIA = {
  photos: [
    ...makePlaceholderItems("holud", 18, "photo"),
    ...makePlaceholderItems("wedding", 18, "photo")
  ],
  videos: [
    ...makePlaceholderItems("holud", 3, "video"),
    ...makePlaceholderItems("wedding", 4, "video")
  ]
};
